### ISSUE TITLE
Update citation

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#123]
Include new contributors @jeffjennings , @kdesoto-astro, M. Delamer, M. Ogborn, and @kadri-nizam

**Comment by jeffjennings** [comment]
Note to do this before next release

**Comment by jeffjennings** [comment]
I moved a few issues for automating an inference loop, creating a command line interface for inference, and testing different cross-val batching approaches out of the [v0.2.0 milestone](https://github.com/MPoL-dev/MPoL/milestone/3) and into a new [milestone](https://github.com/MPoL-dev/MPoL/milestone/5) with that scope. 

Having done that, this issue, #148 and #198 are all that are left for the v0.2.0 milestone, which are all quick to deal with. The new version could be v0.1.13 rather than v0.2.0 if preferred.

**Comment by iancze** [comment]
You (and others) have contributed a ton of new stuff, so I think v0.2.0 is appropriate!
