### ISSUE TITLE
numpy image interfacing convenience functions

### ISSUE THREAD

**Issue by jeffjennings** [MPoL-dev/MPoL#192]
**Is your feature request related to a problem or opportunity? Please describe.**
It would be convenient to have some convenience functions for manipulating numpy image arrays and converting them into mpol-friendly format. I'm thinking of numpy arrays generated from FITS files or mock images generated with numpy (e.g. by frank).

**Describe the solution you'd like**
- utility function to convert a numpy image into an `ImageCube`

**Describe alternatives you've considered**
It could be the user's responsibility to convert numpy image arrays into MPoL formats for manipulation, and the steps are demonstrated in MPoL tutorials. But it would save and potentially some confusion time to wrap the basic functionality in a helper functions. 

**Additional context**
N/A

**How might you be able to help with the development of this feature?**
I'll add this utility function in a linked pull request, and if it's not the ideal solution, we can discuss there or here.

**Comment by iancze** [comment]
I'm of two minds re: this functionality. On one hand, yes, it would be nice to have a one-line function to convert a numpy array into an `ImageCube`, since this is a common-enough operation for the simulated tests we've discussed. On the other hand, it's only replacing about 4 lines. My thought was that there is enough variation in the route to creating an `ImageCube` from mock images (from simulations, real images, color images, PIL output, etc) that a function like `np_to_imagecube` isn't sufficiently general to replace all of these extra pre-processing steps. I think there is value to showing the user how to work with the PyTorch objects directly because I can imagine that sophisticated pre-processing routines would use PyTorch [dataloaders](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html) or torchvision pipelines to create the PyTorch arrays directly. But we should discuss use cases more.

**Comment by jeffjennings** [comment]
I agree with all of that. For the tests I have in mind, `np_to_imagecube` would be sufficient as-is, but like you say it's not all that general. It does save putting the same four lines in several parts of the tests/potentially other places in the code, and the docs still have the full demonstration for users to learn. But if it's not worth the addition, it's really no problem. If that's the case, feel free to close this and delete #193.

**Comment by jeffjennings** [comment]
See #193 for motivation to close this.
