### ISSUE TITLE
Further savings to DirtyImager memory usage

### ISSUE THREAD

**Issue by jeffjennings** [MPoL-dev/MPoL#236]
**Is your feature request related to a problem or opportunity? Please describe.**
Memory footprint of `DirtyImager` was reduced in #230 by making the data (u, v, ReV, ImV, weights) properties of the class. These are only used in `DirtyImager` by the private function `_grid_visibilities` and the function `get_dirty_image` that calls `_grid_visibilities`. The memory footprint could be further reduced, significantly for large datasets, by calling `_grid_visibilities` when `DirtyImager` is instantiated and storing the gridded data, rather than making the loose data properties that have to be pulled into memory by `_grid_visibilities` whenever `get_dirty_image` is called. 

I don't think the loose data really need to be kept in `DirtyImager` for another reason (since no other routine internal to it uses them), do they? If not, I could implement this.

**Comment by iancze** [comment]
I *think* that it is just keeping a reference to the array, not copying it, since arrays are passed by reference.

Before the Hermitian concat operation had not only doubled the size of the array, but also resulted in a new array to keep track of.

One way to check this would be to create a quick branch and implement an operation in DirtyImager that modifies say the self.uu array. It should also be reflected in the original array that was passed into __init__.

**Comment by jeffjennings** [comment]
Yes right and I guess it would require a rewriting of some parts of `GridderBase` too. Anyway, just a thought.

**Comment by iancze** [comment]
My interpretation of how things are working is that `GridderBase` already stores/d values by default, and therefore has/d a minimal memory footprint as far as storing the dataset is concerned.
